import {
  FileText,
  Image,
  ScanText,
  Archive,
  FileSpreadsheet,
  Code,
  QrCode,
  Merge,
  Split,
  Trash2,
  RotateCw,
  Lock,
  Unlock,
  FileImage,
  Minimize2,
  PenTool,
  Hash,
  Layers,
  FileDown,
  FileUp,
  Scissors,
  Move,
  Stamp,
  ListOrdered,
  Shield,
  Crop,
  Maximize2,
  AlignCenter,
  FormInput,
  Signature,
  RefreshCw,
  FlipHorizontal,
  Eraser,
  ImagePlus,
  Languages,
  Table,
  FolderArchive,
  FolderOpen,
  FilePlus,
  FileSearch,
  TextCursor,
  CaseSensitive,
  SpellCheck,
  FileText as TextFile,
  Diff,
  AtSign,
  Link,
  Binary,
  Globe,
  Fingerprint,
  Key,
  Braces,
  FileJson,
  Clock,
  HardDrive,
  Wifi,
  type LucideIcon
} from 'lucide-react'

export interface Tool {
  id: string
  name: string
  nameEn: string
  description: string
  descriptionEn: string
  icon: LucideIcon
  category: string
  acceptedTypes: string[]
  maxFileSize: number // in MB
  maxFiles: number
  outputType: string
  processingTime: 'fast' | 'medium' | 'slow'
}

export interface Category {
  id: string
  name: string
  nameEn: string
  icon: LucideIcon
  color: string
}

export const categories: Category[] = [
  { id: 'pdf', name: 'أدوات PDF', nameEn: 'PDF Tools', icon: FileText, color: 'bg-red-500' },
  { id: 'images', name: 'أدوات الصور', nameEn: 'Image Tools', icon: Image, color: 'bg-green-500' },
  { id: 'ocr', name: 'التعرف الضوئي', nameEn: 'OCR', icon: ScanText, color: 'bg-blue-500' },
  { id: 'archive', name: 'الأرشفة', nameEn: 'Archiving', icon: Archive, color: 'bg-yellow-500' },
  { id: 'documents', name: 'المستندات والبيانات', nameEn: 'Documents & Data', icon: FileSpreadsheet, color: 'bg-purple-500' },
  { id: 'text', name: 'أدوات النص والترميز', nameEn: 'Text & Dev', icon: Code, color: 'bg-cyan-500' },
  { id: 'extras', name: 'أدوات إضافية', nameEn: 'Extras', icon: QrCode, color: 'bg-orange-500' },
]

export const tools: Tool[] = [
  // PDF Tools
  {
    id: 'compress-pdf',
    name: 'ضغط PDF',
    nameEn: 'Compress PDF',
    description: 'تقليل حجم ملفات PDF مع الحفاظ على الجودة',
    descriptionEn: 'Reduce PDF file size while maintaining quality',
    icon: Minimize2,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 10,
    outputType: 'application/pdf',
    processingTime: 'medium'
  },
  {
    id: 'merge-pdf',
    name: 'دمج PDF',
    nameEn: 'Merge PDF',
    description: 'دمج عدة ملفات PDF في ملف واحد',
    descriptionEn: 'Combine multiple PDF files into one',
    icon: Merge,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 20,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'split-pdf',
    name: 'تقسيم PDF',
    nameEn: 'Split PDF',
    description: 'تقسيم ملف PDF إلى ملفات متعددة',
    descriptionEn: 'Split a PDF into multiple files',
    icon: Split,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'fast'
  },
  {
    id: 'extract-pages',
    name: 'استخراج صفحات',
    nameEn: 'Extract Pages',
    description: 'استخراج صفحات محددة من ملف PDF',
    descriptionEn: 'Extract specific pages from a PDF',
    icon: FileDown,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'delete-pages',
    name: 'حذف صفحات',
    nameEn: 'Delete Pages',
    description: 'حذف صفحات من ملف PDF',
    descriptionEn: 'Remove pages from a PDF',
    icon: Trash2,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'reorder-pages',
    name: 'إعادة ترتيب الصفحات',
    nameEn: 'Reorder Pages',
    description: 'إعادة ترتيب صفحات PDF بالسحب والإفلات',
    descriptionEn: 'Reorder PDF pages with drag and drop',
    icon: Move,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'rotate-pages',
    name: 'تدوير الصفحات',
    nameEn: 'Rotate Pages',
    description: 'تدوير صفحات PDF',
    descriptionEn: 'Rotate PDF pages',
    icon: RotateCw,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF إلى صور',
    nameEn: 'PDF to JPG',
    description: 'تحويل صفحات PDF إلى صور',
    descriptionEn: 'Convert PDF pages to images',
    icon: FileImage,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 50,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'medium'
  },
  {
    id: 'jpg-to-pdf',
    name: 'صور إلى PDF',
    nameEn: 'JPG to PDF',
    description: 'تحويل الصور إلى ملف PDF',
    descriptionEn: 'Convert images to a PDF file',
    icon: FileText,
    category: 'pdf',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: 20,
    maxFiles: 50,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'pdf-to-word',
    name: 'PDF إلى Word',
    nameEn: 'PDF to Word',
    description: 'تحويل PDF إلى مستند Word (أفضل جهد)',
    descriptionEn: 'Convert PDF to Word document (best effort)',
    icon: FileText,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 30,
    maxFiles: 1,
    outputType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    processingTime: 'slow'
  },
  {
    id: 'word-to-pdf',
    name: 'Word إلى PDF',
    nameEn: 'Word to PDF',
    description: 'تحويل مستند Word إلى PDF',
    descriptionEn: 'Convert Word document to PDF',
    icon: FileText,
    category: 'pdf',
    acceptedTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
    maxFileSize: 30,
    maxFiles: 5,
    outputType: 'application/pdf',
    processingTime: 'medium'
  },
  {
    id: 'add-watermark',
    name: 'إضافة علامة مائية',
    nameEn: 'Add Watermark',
    description: 'إضافة علامة مائية نصية أو صورة',
    descriptionEn: 'Add text or image watermark',
    icon: Stamp,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'medium'
  },
  {
    id: 'add-page-numbers',
    name: 'ترقيم الصفحات',
    nameEn: 'Add Page Numbers',
    description: 'إضافة أرقام الصفحات إلى PDF',
    descriptionEn: 'Add page numbers to PDF',
    icon: ListOrdered,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'medium'
  },
  {
    id: 'protect-pdf',
    name: 'حماية PDF',
    nameEn: 'Protect PDF',
    description: 'إضافة كلمة مرور لحماية PDF',
    descriptionEn: 'Add password protection to PDF',
    icon: Lock,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'unlock-pdf',
    name: 'إلغاء حماية PDF',
    nameEn: 'Unlock PDF',
    description: 'إزالة كلمة المرور من PDF',
    descriptionEn: 'Remove password from PDF',
    icon: Unlock,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'remove-metadata',
    name: 'إزالة البيانات الوصفية',
    nameEn: 'Remove Metadata',
    description: 'حذف البيانات الوصفية من PDF',
    descriptionEn: 'Remove metadata from PDF',
    icon: Eraser,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 5,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'crop-pdf',
    name: 'قص PDF',
    nameEn: 'Crop PDF',
    description: 'قص هوامش صفحات PDF',
    descriptionEn: 'Crop PDF page margins',
    icon: Crop,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'resize-pages',
    name: 'تغيير حجم الصفحات',
    nameEn: 'Resize Pages',
    description: 'تغيير حجم صفحات PDF (A4/Letter)',
    descriptionEn: 'Resize PDF pages to A4/Letter',
    icon: Maximize2,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'flatten-pdf',
    name: 'تسطيح PDF',
    nameEn: 'Flatten PDF',
    description: 'تسطيح النماذج والتعليقات',
    descriptionEn: 'Flatten forms and annotations',
    icon: Layers,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },
  {
    id: 'sign-pdf',
    name: 'توقيع PDF',
    nameEn: 'Sign PDF',
    description: 'إضافة توقيع صورة إلى PDF',
    descriptionEn: 'Add image signature to PDF',
    icon: Signature,
    category: 'pdf',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'fast'
  },

  // Image Tools
  {
    id: 'convert-image',
    name: 'تحويل صيغة الصورة',
    nameEn: 'Convert Image',
    description: 'تحويل بين PNG/JPG/WebP/AVIF/GIF/TIFF/BMP',
    descriptionEn: 'Convert between PNG/JPG/WebP/AVIF/GIF/TIFF/BMP',
    icon: RefreshCw,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'compress-image',
    name: 'ضغط الصور',
    nameEn: 'Compress Image',
    description: 'تقليل حجم الصور مع الحفاظ على الجودة',
    descriptionEn: 'Reduce image size while maintaining quality',
    icon: Minimize2,
    category: 'images',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'resize-image',
    name: 'تغيير حجم الصورة',
    nameEn: 'Resize Image',
    description: 'تغيير أبعاد الصورة',
    descriptionEn: 'Change image dimensions',
    icon: Maximize2,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'crop-image',
    name: 'قص الصورة',
    nameEn: 'Crop Image',
    description: 'قص جزء من الصورة',
    descriptionEn: 'Crop a portion of the image',
    icon: Crop,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 50,
    maxFiles: 10,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'rotate-flip-image',
    name: 'تدوير وقلب الصورة',
    nameEn: 'Rotate & Flip Image',
    description: 'تدوير أو قلب الصورة',
    descriptionEn: 'Rotate or flip images',
    icon: FlipHorizontal,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'remove-exif',
    name: 'إزالة بيانات EXIF',
    nameEn: 'Remove EXIF',
    description: 'حذف البيانات الوصفية من الصور',
    descriptionEn: 'Remove metadata from images',
    icon: Eraser,
    category: 'images',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/tiff'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'watermark-image',
    name: 'علامة مائية للصور',
    nameEn: 'Watermark Image',
    description: 'إضافة علامة مائية للصور',
    descriptionEn: 'Add watermark to images',
    icon: Stamp,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/*',
    processingTime: 'fast'
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC إلى JPG',
    nameEn: 'HEIC to JPG',
    description: 'تحويل صور iPhone HEIC إلى JPG',
    descriptionEn: 'Convert iPhone HEIC images to JPG',
    icon: FileImage,
    category: 'images',
    acceptedTypes: ['image/heic', 'image/heif'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'image/jpeg',
    processingTime: 'fast'
  },
  {
    id: 'images-to-pdf',
    name: 'صور إلى PDF',
    nameEn: 'Images to PDF',
    description: 'تحويل مجموعة صور إلى PDF',
    descriptionEn: 'Convert multiple images to PDF',
    icon: FileText,
    category: 'images',
    acceptedTypes: ['image/*'],
    maxFileSize: 20,
    maxFiles: 50,
    outputType: 'application/pdf',
    processingTime: 'medium'
  },
  {
    id: 'pdf-to-images',
    name: 'PDF إلى صور',
    nameEn: 'PDF to Images',
    description: 'تحويل كل صفحة PDF إلى صورة',
    descriptionEn: 'Convert each PDF page to an image',
    icon: Image,
    category: 'images',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 50,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'medium'
  },

  // OCR Tools
  {
    id: 'ocr-image-to-text',
    name: 'استخراج نص من صورة',
    nameEn: 'OCR Image to Text',
    description: 'التعرف على النص في الصور (عربي + إنجليزي)',
    descriptionEn: 'Extract text from images (Arabic + English)',
    icon: ScanText,
    category: 'ocr',
    acceptedTypes: ['image/*'],
    maxFileSize: 20,
    maxFiles: 10,
    outputType: 'text/plain',
    processingTime: 'slow'
  },
  {
    id: 'ocr-pdf-to-text',
    name: 'استخراج نص من PDF',
    nameEn: 'OCR PDF to Text',
    description: 'استخراج النص من PDF الممسوح',
    descriptionEn: 'Extract text from scanned PDF',
    icon: FileSearch,
    category: 'ocr',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 30,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'slow'
  },
  {
    id: 'searchable-pdf',
    name: 'PDF قابل للبحث',
    nameEn: 'Searchable PDF',
    description: 'تحويل PDF ممسوح إلى قابل للبحث',
    descriptionEn: 'Convert scanned PDF to searchable',
    icon: FileSearch,
    category: 'ocr',
    acceptedTypes: ['application/pdf'],
    maxFileSize: 30,
    maxFiles: 1,
    outputType: 'application/pdf',
    processingTime: 'slow'
  },
  {
    id: 'extract-table-to-csv',
    name: 'استخراج جدول إلى CSV',
    nameEn: 'Extract Table to CSV',
    description: 'استخراج الجداول من PDF إلى CSV',
    descriptionEn: 'Extract tables from PDF to CSV',
    icon: Table,
    category: 'ocr',
    acceptedTypes: ['application/pdf', 'image/*'],
    maxFileSize: 20,
    maxFiles: 1,
    outputType: 'text/csv',
    processingTime: 'slow'
  },

  // Archive Tools
  {
    id: 'zip-create',
    name: 'إنشاء ZIP',
    nameEn: 'Create ZIP',
    description: 'ضغط الملفات في أرشيف ZIP',
    descriptionEn: 'Compress files into a ZIP archive',
    icon: FolderArchive,
    category: 'archive',
    acceptedTypes: ['*/*'],
    maxFileSize: 100,
    maxFiles: 50,
    outputType: 'application/zip',
    processingTime: 'fast'
  },
  {
    id: 'zip-extract',
    name: 'فك ZIP',
    nameEn: 'Extract ZIP',
    description: 'استخراج محتويات أرشيف ZIP',
    descriptionEn: 'Extract contents from ZIP archive',
    icon: FolderOpen,
    category: 'archive',
    acceptedTypes: ['application/zip', 'application/x-zip-compressed'],
    maxFileSize: 200,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'fast'
  },
  {
    id: '7z-extract',
    name: 'فك 7Z',
    nameEn: 'Extract 7Z',
    description: 'استخراج محتويات أرشيف 7Z',
    descriptionEn: 'Extract contents from 7Z archive',
    icon: FolderOpen,
    category: 'archive',
    acceptedTypes: ['application/x-7z-compressed'],
    maxFileSize: 200,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'medium'
  },
  {
    id: 'tar-extract',
    name: 'فك TAR',
    nameEn: 'Extract TAR',
    description: 'استخراج محتويات أرشيف TAR',
    descriptionEn: 'Extract contents from TAR archive',
    icon: FolderOpen,
    category: 'archive',
    acceptedTypes: ['application/x-tar'],
    maxFileSize: 200,
    maxFiles: 1,
    outputType: 'application/zip',
    processingTime: 'fast'
  },
  {
    id: 'tar-gz-create',
    name: 'إنشاء TAR.GZ',
    nameEn: 'Create TAR.GZ',
    description: 'ضغط الملفات في أرشيف TAR.GZ',
    descriptionEn: 'Compress files into TAR.GZ archive',
    icon: FolderArchive,
    category: 'archive',
    acceptedTypes: ['*/*'],
    maxFileSize: 100,
    maxFiles: 50,
    outputType: 'application/gzip',
    processingTime: 'fast'
  },

  // Documents & Data Tools
  {
    id: 'csv-to-xlsx',
    name: 'CSV إلى Excel',
    nameEn: 'CSV to Excel',
    description: 'تحويل ملف CSV إلى Excel',
    descriptionEn: 'Convert CSV file to Excel',
    icon: FileSpreadsheet,
    category: 'documents',
    acceptedTypes: ['text/csv', 'application/csv'],
    maxFileSize: 50,
    maxFiles: 5,
    outputType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    processingTime: 'fast'
  },
  {
    id: 'xlsx-to-csv',
    name: 'Excel إلى CSV',
    nameEn: 'Excel to CSV',
    description: 'تحويل ملف Excel إلى CSV',
    descriptionEn: 'Convert Excel file to CSV',
    icon: FileSpreadsheet,
    category: 'documents',
    acceptedTypes: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'],
    maxFileSize: 50,
    maxFiles: 5,
    outputType: 'text/csv',
    processingTime: 'fast'
  },
  {
    id: 'csv-merge',
    name: 'دمج ملفات CSV',
    nameEn: 'Merge CSV Files',
    description: 'دمج عدة ملفات CSV في ملف واحد',
    descriptionEn: 'Merge multiple CSV files into one',
    icon: Merge,
    category: 'documents',
    acceptedTypes: ['text/csv', 'application/csv'],
    maxFileSize: 50,
    maxFiles: 20,
    outputType: 'text/csv',
    processingTime: 'fast'
  },
  {
    id: 'csv-deduplicate',
    name: 'إزالة التكرارات من CSV',
    nameEn: 'CSV Deduplicate',
    description: 'إزالة الصفوف المكررة من CSV',
    descriptionEn: 'Remove duplicate rows from CSV',
    icon: Trash2,
    category: 'documents',
    acceptedTypes: ['text/csv', 'application/csv'],
    maxFileSize: 50,
    maxFiles: 1,
    outputType: 'text/csv',
    processingTime: 'fast'
  },

  // Text & Dev Tools
  {
    id: 'case-converter',
    name: 'محول الحالة',
    nameEn: 'Case Converter',
    description: 'تحويل النص بين الأحرف الكبيرة والصغيرة',
    descriptionEn: 'Convert text between uppercase and lowercase',
    icon: CaseSensitive,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 5,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'word-counter',
    name: 'عداد الكلمات',
    nameEn: 'Word Counter',
    description: 'عد الكلمات والأحرف والجمل',
    descriptionEn: 'Count words, characters, and sentences',
    icon: Hash,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 5,
    maxFiles: 1,
    outputType: 'application/json',
    processingTime: 'fast'
  },
  {
    id: 'text-diff',
    name: 'مقارنة النصوص',
    nameEn: 'Text Diff',
    description: 'مقارنة نصين وإظهار الفروقات',
    descriptionEn: 'Compare two texts and show differences',
    icon: Diff,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 5,
    maxFiles: 2,
    outputType: 'text/html',
    processingTime: 'fast'
  },
  {
    id: 'extract-emails',
    name: 'استخراج الإيميلات',
    nameEn: 'Extract Emails',
    description: 'استخراج عناوين البريد الإلكتروني من النص',
    descriptionEn: 'Extract email addresses from text',
    icon: AtSign,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 5,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'extract-urls',
    name: 'استخراج الروابط',
    nameEn: 'Extract URLs',
    description: 'استخراج الروابط من النص',
    descriptionEn: 'Extract URLs from text',
    icon: Link,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 5,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'base64-encode-decode',
    name: 'Base64 تشفير/فك',
    nameEn: 'Base64 Encode/Decode',
    description: 'تشفير أو فك تشفير Base64',
    descriptionEn: 'Encode or decode Base64',
    icon: Binary,
    category: 'text',
    acceptedTypes: ['text/plain', '*/*'],
    maxFileSize: 10,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'url-encode-decode',
    name: 'URL تشفير/فك',
    nameEn: 'URL Encode/Decode',
    description: 'تشفير أو فك تشفير URL',
    descriptionEn: 'Encode or decode URL',
    icon: Globe,
    category: 'text',
    acceptedTypes: ['text/plain'],
    maxFileSize: 1,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'hash-generator',
    name: 'توليد Hash',
    nameEn: 'Hash Generator',
    description: 'توليد MD5/SHA1/SHA256/SHA512',
    descriptionEn: 'Generate MD5/SHA1/SHA256/SHA512',
    icon: Fingerprint,
    category: 'text',
    acceptedTypes: ['text/plain', '*/*'],
    maxFileSize: 100,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'uuid-generator',
    name: 'توليد UUID',
    nameEn: 'UUID Generator',
    description: 'توليد معرفات UUID فريدة',
    descriptionEn: 'Generate unique UUID identifiers',
    icon: Fingerprint,
    category: 'text',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'password-generator',
    name: 'توليد كلمة مرور',
    nameEn: 'Password Generator',
    description: 'توليد كلمات مرور آمنة',
    descriptionEn: 'Generate secure passwords',
    icon: Key,
    category: 'text',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'json-formatter',
    name: 'تنسيق JSON',
    nameEn: 'JSON Formatter',
    description: 'تنسيق وتحقق وتصغير JSON',
    descriptionEn: 'Format, validate, and minify JSON',
    icon: Braces,
    category: 'text',
    acceptedTypes: ['application/json', 'text/plain'],
    maxFileSize: 10,
    maxFiles: 1,
    outputType: 'application/json',
    processingTime: 'fast'
  },
  {
    id: 'csv-json-converter',
    name: 'CSV ↔ JSON',
    nameEn: 'CSV ↔ JSON Converter',
    description: 'تحويل بين CSV و JSON',
    descriptionEn: 'Convert between CSV and JSON',
    icon: FileJson,
    category: 'text',
    acceptedTypes: ['text/csv', 'application/json', 'text/plain'],
    maxFileSize: 10,
    maxFiles: 1,
    outputType: 'text/plain',
    processingTime: 'fast'
  },

  // Extras
  {
    id: 'qr-code-generator',
    name: 'توليد QR Code',
    nameEn: 'QR Code Generator',
    description: 'إنشاء QR Code للروابط والنصوص',
    descriptionEn: 'Generate QR Code for URLs and text',
    icon: QrCode,
    category: 'extras',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'image/png',
    processingTime: 'fast'
  },
  {
    id: 'barcode-generator',
    name: 'توليد Barcode',
    nameEn: 'Barcode Generator',
    description: 'إنشاء باركود Code128/EAN',
    descriptionEn: 'Generate Code128/EAN barcode',
    icon: Code,
    category: 'extras',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'image/png',
    processingTime: 'fast'
  },
  {
    id: 'unix-time-converter',
    name: 'محول Unix Time',
    nameEn: 'Unix Time Converter',
    description: 'تحويل Unix timestamp إلى تاريخ والعكس',
    descriptionEn: 'Convert Unix timestamp to date and vice versa',
    icon: Clock,
    category: 'extras',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
  {
    id: 'file-size-converter',
    name: 'محول حجم الملفات',
    nameEn: 'File Size Converter',
    description: 'تحويل بين وحدات حجم الملفات',
    descriptionEn: 'Convert between file size units',
    icon: HardDrive,
    category: 'extras',
    acceptedTypes: [],
    maxFileSize: 0,
    maxFiles: 0,
    outputType: 'text/plain',
    processingTime: 'fast'
  },
]

export function getToolById(id: string): Tool | undefined {
  return tools.find(t => t.id === id)
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(t => t.category === categoryId)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return tools.filter(t =>
    t.name.includes(q) ||
    t.nameEn.toLowerCase().includes(q) ||
    t.description.includes(q) ||
    t.descriptionEn.toLowerCase().includes(q)
  )
}
